[versions]
agp = "8.12.0"
firebaseBom = "34.1.0"
kotlin = "1.9.24"
annotation = "1.6.0"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
coreKtx = "1.15.0"
lifecycleViewmodelKtx = "2.8.7"
material = "1.12.0"
activity = "1.9.3"
openpdf = "1.3.30"
itextpdf = "5.5.13.2"
itext7Core = "7.1.17"
payview = "1.0.3"
zxingCore = "3.4.1"
zxingAndroidEmbedded = "4.3.0"
junit = "4.13.2"
junitExt = "1.2.1"
espresso = "3.6.1"
firebaseCrashlytics = "19.3.0"
googleGms = "4.4.2"
googleFirebaseCrashlytics = "3.0.2"
firebaseFirestore = "26.0.1"

[libraries]
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
com-google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
openpdf = { group = "com.github.librepdf", name = "openpdf", version.ref = "openpdf" }
itextpdf = { group = "com.itextpdf", name = "itextpdf", version.ref = "itextpdf" }
itext7-core = { group = "com.itextpdf", name = "itext7-core", version.ref = "itext7Core" }
payview = { module = "com.github.fevziomurtekin:PayView", version.ref = "payview" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxingCore" }
zxing-android-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms = { id = "com.google.gms.google-services", version.ref = "googleGms" }
firebase-crashlytics-plugin = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }
